import { Router } from "express";
import { auth } from "../../middlewares/authenticate";
import { validate } from "../../middlewares/validate";
import { paymentController } from "./payment.controller";
import { initializeCheckoutSchema } from "./payment.validator";
const paymentRouter = Router();
paymentRouter.post("/paystack/webhook", paymentController.webhook);
paymentRouter.post("/checkout", auth, validate(initializeCheckoutSchema), paymentController.initialize);
paymentRouter.get("/verify/:reference", auth, paymentController.verify);
export default paymentRouter;
